### ISSUE TITLE
Rename this project and nuget package

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Interop.Dynamic#1]
Hi @jbtule,

I'm doing an audit of F# nuget packages searching for "FSharp".

Please rename this project (and more importantly the corresponding nuget package) to follow the [recently published guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html), e.g.
- FSharp.Core.Dynamic (this seems an appropriate use of "Core")
- FSharp.Interop.Dynamic (this seems an appropriate new 2nd-level namespace)

Thanks!
Don

**Comment by jbtule** [comment]
I'll switch it to `FSharp.Interop.Dynamic`.

**Comment by dsyme** [comment]
Super thanks

**Comment by dsyme** [comment]
Hi @jbtule  - Could you republish the nuget package too please, as http://www-0.nuget.org/packages/FSharp.Interop.Dynamic/ (and then if you have time please hide all the old editions of http://www-0.nuget.org/packages/FSharp.Dynamic/ from the nuget index)

thanks!

**Comment by jbtule** [comment]
Done.
