### ISSUE TITLE
Bug in dynamic fixed by https://github.com/dotnet/corefx/pull/23512

### ISSUE THREAD

**Issue by pshrosbree** [fsprojects/FSharp.Interop.Dynamic#12]
### Description

Unit tests skip .net core 2.0 but bug in dynamic has been fixed by https://github.com/dotnet/corefx/pull/23512

### Repro steps

See unit tests

### Expected behavior

Unit tests are not ignore in .NET Core 2

### Actual behavior

Unit test are ignored in .NET Core 2

### Known workarounds

None

**Comment by jbtule** [comment]
I've been tracking it. It supposedly hasn't made it into a release yet, even though it's been fixed in source. 2.0.3 they are expecting sometime this week maybe? https://github.com/dotnet/corefx/issues/21689
