### ISSUE TITLE
How can I invoke a dynamic object?

### ISSUE THREAD

**Issue by lostmsu** [fsprojects/FSharp.Interop.Dynamic#21]
I have an `Invokable` object returned from a C# **property** of type `dynamic`. In C# I can do `MyClass.Invokable(some, parameters, here)`.

However, in F# `MyClass.Invokable?()` leads to _error FS0010: Unexpected symbol ')' in expression_

What is the correct syntax to make this call?

**Comment by jbtule** [comment]
`!? MyClass.Invokable (some, parameters, here)`  

If i understand this correctly to be a static property `Invokable` on class `MyClass`

https://github.com/fsprojects/FSharp.Interop.Dynamic/blob/739f519d1277de69315015b8e47045f90f67c6b3/FSharp.Interop.Dynamic/TopLevelOperators.fs#L23-L33

**Comment by lostmsu** [comment]
@jbtule should add it to the README
