### ISSUE TITLE
New maintainer sought

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Interop.Dynamic#28]
@jbtule I'm guessing you're not maintaining this any more?

If anyone would like to maintain this library please let us know, we can add you

**Comment by AtwoodTM** [comment]
Hi @dsyme, I will do it.  I am working on a project that needs to use this project.  I already spent my Sunday updating it to .NET 6 and all the tests still work.  However, I still need to update the docs to the latest version of FSharp.Formatting and moving the build script over to GitHub Actions.

**Comment by dsyme** [comment]
@AtwoodTM Great!

**Comment by dsyme** [comment]
@AtwoodTM I've made you maintainer on this repo. Thanks

**Comment by dsyme** [comment]
I've added a publishing key to allow maintainers to use CI to push new package versions. This technique is used in other repos e.g. https://github.com/fsprojects/FSharp.Collections.ParallelSeq/blob/main/.github/workflows/publish.yml#L40.

The name of the key is under https://github.com/fsprojects/FSharp.Interop.Dynamic/settings/secrets/actions
