### ISSUE TITLE
Move into FSharp.Core?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Interop.Dynamic#7]
@jbtule Should we be moving this implementation into FSharp.Core?  Perhaps requiring an explicit

    open FSharp.Core.Dynamic

We would require an F# language suggestion and RFC for this.

Just wondering what you and others think

Thanks
Don

**Comment by jbtule** [comment]
I don't think so, right now it's wrapping `Dynamitey` which is wrapping [Microsoft.CSharp](https://www.nuget.org/packages/Microsoft.CSharp/). I don't think `FSharp.Core` wants a dependency on `Microsoft.CSharp`, right?

**Comment by dsyme** [comment]
@jbtule That's correct, good point.
