### ISSUE TITLE
Add More Operators

### ISSUE THREAD

**Issue by jbtule** [fsprojects/FSharp.Interop.Dynamic#8]
As seen in https://github.com/pythonnet/pythonnet/issues/112 can't use plus operators.

However in [Dynamitey](https://github.com/ekonbenefits/dynamitey), I do have support for every operator c# dynamic does using `Dynamic.InvokeBinaryOperator`  So it wouldn't be hard to add, would just have to come up with operators that makes sense.

**Comment by dsyme** [comment]
Yes, an F# standard way of doing this would be great

I think you can feel free to reuse the NullableOperators? https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/linq.nullableoperators-module-%5Bfsharp%5D as long as you have an explicit open for say ``open FSharp.Interop.Dynamic.Operators``


The NullableOperators are used incredibly rarely and only in LINQ queries after an explicit open. We really only added them for SQL completeness.  I don't like what we did here particularly but, well, it is what it is and at least it is hidden away in normal usage

**Comment by jbtule** [comment]
on nuget 4.0.3-beta95
